### ISSUE TITLE
make a template repo

### ISSUE THREAD

**Issue by lunebellec** [brainhack-proceedings/docs#1]
This repo would have the latex template, an example compiled document, as well as the .yml configuration file (or a config script to initialize this yaml file. The content can be adapted from:
https://github.com/Brainhack-Proceedings-2015/Craddock-AMX-Centrality

The (now empty) template repo can be found here:
https://github.com/brainhack-proceedings/template

**Comment by agahkarakuzu** [comment]
@pbellec I can do this and add an action to compile PDF at each push to the master.

**Comment by lunebellec** [comment]
amazing! please ping @brainhack-proceedings/admin and create issues if you need help with anything.

**Comment by complexbrains** [comment]
I will close this issue since already have a working template repo. I am hoping it is done.
