### ISSUE TITLE
Will we explicitely mention to review all objects (including code review)?

### ISSUE THREAD

**Issue by katjaq** [brainhack-proceedings/docs#14]
We could include a mention of this in the doc.

**Comment by lunebellec** [comment]
This was brought up at brainhack DC as well. I am not personally in favour of reviewing all objects. Typically polishing code or data for review is a long arduous process, and there are dedicated publishing avenues for these objects. I would only make sure we encourage authors to share code and data, and have them properly referenced in the proceedings. But I don't have a strong opinion on this.

**Comment by katjaq** [comment]
Thank you, @pbellec . Yes, I opened this issue after Brainhack Global DC :) My computer crashed and I couldn't follow the conversation. I agree with you, thank you for sharing your thoughts. I will close this issue.
