### ISSUE TITLE
central repo

### ISSUE THREAD

**Issue by lunebellec** [brainhack-proceedings/docs#3]
We need a central website, which will ultimately be rendered at proceedings.brainhack.org

This would be adapted from the brainweb.
https://brain-web.github.io/projects/

For now, it would render all the repo inside brainhack-proceedings, which have the "paper" tag.
I have created an empty repo for that project:
https://github.com/brainhack-proceedings/proceedings.brainhack.org

**Comment by katjaq** [comment]
ok! fantastic! will go ahead asap and ping once a draft is up!

**Comment by complexbrains** [comment]
I close this issue given we have the functioning repo.
